site_name: Linux wiki
repo_url : https://github.com/cheperboy/linux/
docs_dir : docs/ 
# dev_addr: 0.0.0.0:8002 # commented because fail compilation in production(readthedocs)

#theme: readthedocs, material, mkdocs
theme:
  name: 'readthedocs'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  navigation_depth: 4
  collapse_navigation: false
  features:
    - toc.integrate    
nav:
    - index.md
    - server-ubuntu.md
    - server-admin.md
    - server-security.md
    - network.md
    - Linux tools: linux_tools.md
    - Dev tools: dev.md
    - Dot Files: dotfiles.md
    - Bash: bash.md
    - Docker: docker.md
    - Backup: backup.md
    - Raspberry install OS: raspberry_install_raspbian.md
    - Raspberry hardware: raspberry.md
    - Web: web.md
    - Python : python.md
    - python_script_template.md
    - gmail.md
    - snmp.md
    - links.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - footnotes
  - meta
  - markdown_include.include:
      base_path: .

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

