site_name: Linux wiki
repo_url : https://github.com/cheperboy/linux/
docs_dir : docs/ 
# dev_addr: 0.0.0.0:8002 # commented because fail compilation in production(readthedocs)

# theme: readthedocs
theme:
  name: 'readthedocs'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  features:
#     - toc.integrate    
nav:
    - Home: index.md
    - Server Admin: server_admin.md
    - Bash: bash.md
    - Backup: backup.md
    - Docker: docker.md
    - Raspberry install OS: raspberry_install_raspbian.md
    - Dot Files: dotfiles.md
    - Linux tools: linux_tools.md
    - Raspberry hardware: raspberry.md
    - Security: security.md
    - Dev tools: dev.md
    - Web: web.md
    - Python : python.md
    - Kivy : kivy.md
    - Python script template: python_script_template.md
    - Network: network.md
    - gmail.md
    - links.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - footnotes
  - meta
  - markdown_include.include:
      base_path: .

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

